<%// Author: Brett Leber
  // Version: $Revision: 5840 $
  // Last modified by: $Author: bleber $
  // Last modified on: $Date: 2009-10-19 15:00:35 -0400 (Mon, 19 Oct 2009) $
  // $KeyWordsOff: $
  //
%>

<h2>Logging Activity</h2>

    <p>When activated, this report provides a logging diagnostic by displaying counts of all recent
    log messages received by the <a href="help?page=logging#logging-urls">logging server</a>, organized
    by dataset and student session. It is intended for use by technical researchers or staff who are in
    the process of verifying logging activity from a study site.</p>
    
    <p>Since this report is generated by querying the live logging database, and using it has the
    potential to affect that database, we are requesting that you agree to follow the guidelines at the
    top of the page before using the page.</p>
    
    <h4>Column Descriptions</h4>
    
    <dl>
        <dt>Session ID</dt>
        <dd>A unique identifier that identifies the student session with the tutor. 
        Although this varies by logging implementation, expect one session ID for every student session
        (an instance of a user logged in and generating log data). Although session ID should be a 
        guaranteed unique identifier (a GUID), a duplicate session ID is possible, and the presence
        of duplicates could skew the data in this report.</dd>
    
        <dt>First Message Receipt Time</dt>
        <dd>The time on the DataShop server when the first message of the session was received. Note
        that this is first message for the session <em>within the specified time frame</em>.</dd>
    
        <dt>Last Message Receipt Time</dt>
        <dd>The time on the DataShop server when the last message of the session was received.</dd>
    
        <dt>Total</dt>
        <dd>The total number of log messages (Context, Tool, Tutor, and Plain messages) received
        within the specified time frame.</dd>
    
        <dt>Context</dt>
        <dd>The number of <a href="https://pslcdatashop.web.cmu.edu/dtd/guide/context_message.html">context
        messages</a> received within the specified time frame. A typical number of context messages 
        is one per problem or activity.</dd>
    
        <dt>Tool</dt>
        <dd>The number of <a href="https://pslcdatashop.web.cmu.edu/dtd/guide/tool_message.html">tool
        messages</a> received within the specified time frame. A typical number of tool messages 
        is one per click or other student action.</dd>
    
        <dt>Tutor</dt>
        <dd>The number of <a href="https://pslcdatashop.web.cmu.edu/dtd/guide/tutor_message.html">tutor
        messages</a> received within the specified time frame. A typical number of tool messages is 
        one per click or other student action.</dd>
    
        <dt>Plain</dt>
        <dd>The number of <a href="https://pslcdatashop.web.cmu.edu/dtd/guide/message_message.html">plain
        messages</a> received within the specified time frame. The number of plain messages, or 
        generic messages repurposed by the tutoring system, varies more widely than the other message 
        types. For most systems, this message type should be used far less than the other types.</dd>
    </dl>

