<%@ include file="/header-help.jspf"%>

    <h2>Tab-delimited format</h2>

    <p>You can import a tab-delimited text file of transaction data similar to that
    generated by the DataShop <a href="help?page=export#table-by-tx">transaction export</a>.
    Use the <a href="UploadDataset">Upload Dataset page</a> to upload and verify
    your file(s). You may want to import data as tab-delimited text to:</p>

    <ul class="concise">
        <li>create a smaller dataset from an existing one</li>
        <li>rename problems or steps</li>
        <li>clean up an existing dataset</li>
        <li>add data to DataShop without creating XML</li>
    </ul>

    <p>Read more about the <a href="help?page=import#import-process">import process</a>.

    <p><strong>Note:</strong> If you want to create a new domain KC model for an existing dataset
    in DataShop, use the <a href="help?page=kcm">KC Model export/import feature</a>.</p>

    <h3>Format Documentation</h3>
    <p style="margin-bottom:0">Import file column requirements are described below.</p>
    <div>
        <a href="/about/cheatsheet.html"><img src="images/help/cheatsheet_thumb.png" style="border: none;" /></a>
        <p style="float:left;margin-top:10px">For a handy list of columns, check out our printable
        <a href="/about/cheatsheet.html">DataShop Cheat Sheet</a>.</p>
    </div>

    <table id="import-columns">
        <col style="width:14em" />
        <col style="width:3em" />
        <col style="width:27em" />
        <col style="width:6em" />
    <thead>
        <tr>
        <th>Column</th>
        <th>Required?</th>
        <th>Additional Description</th>
        <th>Size Limit (characters)</th></tr>
    </thead>
    <tbody>
        <tr class="odd">
          <td>Anon Student Id</td>
          <td>*</td>
          <td>An anonymized student identifier.</td>
          <td>&le; 55</td>
        </tr>
      <tr>
        <td>Session Id</td>
        <td>*</td>
        <td>A dataset-unique string that identifies the user's session with the tutor.</td>
        <td>&le; 255</td>
      </tr>
      <tr class="odd">
        <td>Time</td>
        <td>*</td>
        <td>Local time when the transaction occurred. For instance, if a student types "25" and presses return, the
        transaction time is at the point in which they press return. Must be given in one of
        the following <a href="#note-2">standard time formats [1]</a></td>
        <td></td>
      </tr>
      <tr>
        <td>Time Zone</td>
        <td></td>
        <td>Local time zone ID as provided by the zoneinfo
        (or tz) database. Select a time zone name from the "TZ" column in this <a
        href="http://en.wikipedia.org/wiki/List_of_zoneinfo_time_zones">List of zoneinfo time
        zones</a>.</td>
        <td>&le; 50</td>
      </tr>
      <tr class="odd">
        <td>Student Response Type</td>
        <td></td>
        <td>A semantic description
        of the event. DataShop-expected values are <code>ATTEMPT</code> or
        <code>HINT_REQUEST</code>. See the corresponding "Tutor Response Type" below.</td>
        <td>&le; 30</td>
      </tr>
      <tr>
        <td>Student Response Subtype</td>
        <td></td>
        <td>A further classification of student response type.</td>
        <td>&le; 30</td>
      </tr>
      <tr class="odd">
        <td>Tutor Response Type</td>
        <td></td>
        <td>A semantic description of the tutor's response. DataShop-expected values are <code>RESULT</code> or
        <code>HINT_MSG</code>. See the corresponding "Student Response Type" above.</td>
        <td>&le; 30</td>
      </tr>
      <tr>
        <td>Tutor Response Subtype</td>
        <td></td>
        <td>A further classification of tutor response type.</td>
        <td>&le; 30</td>
      </tr>
      <tr class="odd">
        <td>Level ()</td>
        <td>*</td>
        <td>A <em>Dataset Level</em>.
        An example of the correct use of this column heading is <code>Level (Unit)</code>, where
        "Unit" is the dataset level <strong>title</strong> and the value in the column is the level
        <strong>name</strong> (e.g., "Understanding Fractions"). The Level column
        should always be of the format <code>Level (level_title)</code>.
        The level title must be &le; 100 characters
        and consist of letters, numbers, dashes, underscores, and spaces.
        If a dataset level title is
        not included, it will become "Default". Multiple Level columns are OK. For additional
        description, see the <a
        href="http://pslcdatashop.org/dtd/guide/context_message.html#element.dataset.level">level
        element</a> in the Guide. In tutor-message format XML, level "title" is referred to
        as "type".</td>
        <td>&le; 100</td>
      </tr>
      <tr>
        <td>Problem Name</td>
        <td>*</td>
        <td>The name of the problem or activity.</td>
        <td>&le; 255</td>
      </tr>
      <tr class="odd">
        <td>Problem View</td>
        <td></td>
        <td>The number of times the student encountered the problem so far.
        This counter increases with each instance of the same problem. If this column
        is not provided you must provide the <strong>Problem Start Time</strong>; it
        will be used to determine the Problem View. If both are provided, but it is
        determined that they do not agree, the Problem View will not be recomputed.
        A longer description of problem view, including how it is determined if it's
        not present in the imported data, is available <a href="/help?page=export#table-by-student-step">here</a>.</td>
        <td></td>
      </tr>
      <tr>
        <td>Problem Start Time</td>
        <td></td>
        <td>The time the problem is shown to the student. Must be given in one of the
        <a href="#note-2">standard time formats [1]</a>. This column is used to determine
        the <strong>Problem View</strong> if it is not given. If both are provided, but it
        is determined that they do not agree, the Problem View will not be recomputed. A
        longer description of problem start time, including how it is determined if it's
        not present in the imported data, is available <a href="/help?page=export#table-by-student-problem">here</a>.</td>
        <td></td>
      </tr>
      <tr class="odd">
        <td>Step Name</td>
        <td><a href="#note-1">&dagger;</a></td>
        <td>The name of a discrete problem-solving step. Include a step name for a transaction
        if the transaction also has a Tutor Response Type and an Outcome.
        Otherwise, <em>Attempt At Step</em> will not be calculated.</td>
        <td>&le; 255</td>
      </tr>
      <tr>
        <td>Attempt At Step</td>
        <td></td>
        <td><strong>DataShop ignores the values in this column when processing the import
        file</strong>. "Attempt at Step" is computed from the rest of
        the transaction data, but only if <em>Step Name</em> is provided.</td>
        <td></td>
      </tr>
      <tr class="odd">
        <td>Outcome</td>
        <td></td>
        <td>The tutor's evaluation of the action, if applicable. DataShop prefers the
        values <code>CORRECT</code>, <code>INCORRECT</code>, or <code>HINT</code>.</td>
        <td>&le; 30</td>
      </tr>
      <tr>
        <td>Selection</td>
        <td><a href="#note-1">&dagger;</a></td>
        <td>A description of the interface element that
        the student selected or interacted with. Multiple Selection columns are OK. Also see <a
        href="http://pslcdatashop.org/dtd/guide/tool_message.html#element.event_descriptor">Selection</a>
        in the Guide.</td>
        <td>&le; 255</td>
      </tr>
      <tr class="odd">
        <td>Action</td>
        <td><a href="#note-1">&dagger;</a></td>
        <td>A description of the manipulation
        applied to the selection. Multiple Action columns are OK.</td>
        <td>&le; 255</td>
      </tr>
      <tr>
        <td>Input</td>
        <td></td>
        <td>The input the student submitted. Multiple Input columns are OK. Also see <a
        href="http://pslcdatashop.org/dtd/guide/tool_message.html#element.event_descriptor">Input</a>
        in the Guide.</td>
        <td>&le; 255</td>
      </tr>
      <tr class="odd">
        <td>Feedback Text</td>
        <td></td>
        <td>The body of a hint, success, or error message shown to the student.</td>
        <td>&le; 65,535</td>
      </tr>
      <tr>
        <td>Feedback Classification</td>
        <td></td>
        <td>A further classification of the outcome. See <a
        href="http://pslcdatashop.org/dtd/guide/tutor_message.html#element.action_evaluation">action_evaluation
        / classification</a> in the Guide. Note that if Feedback Classification has a value, Feedback Text must have a value
        as well.</td>
        <td>&le; 255</td>
      </tr>
      <tr class="odd">
        <td>Help Level</td>
        <td></td>
        <td>Applicable only to hints, this is the current hint level/depth. If given, value must be a number.</td>
        <td></td>
      </tr>
      <tr>
        <td>Total Num Hints</td>
        <td></td>
        <td>Total number of hints available to the student for this step. If given, value must be a number.</td>
        <td></td>
      </tr>
      <tr class="odd">
        <td>Condition Name</td>
        <td></td>
        <td>A study/experimental condition. Must always be paired with Condition Type, even
        if a condition does not have a condition type. Multiple Condition Name columns are OK. See <a
        href="http://pslcdatashop.org/dtd/guide/context_message.html#element.condition">condition</a>
        in the Guide.</td>
        <td>&le; 80</td>
      </tr>
      <tr>
        <td>Condition Type</td>
        <td></td>
        <td>A condition classification. Must always
        be paired with Condition Name, even if a condition does not have a condition type. Multiple
        Condition Type columns are OK. If Condition Type is specified, Condition Name must have a value as well. </td>
        <td>&le; 255</td>
      </tr>
      <tr class="odd">
        <td>KC ()</td>
        <td></td>
        <td>A <a href="help?page=terms#kc">knowledge component</a>.
        An example of the correct use of this column heading could be <code>KC (Area)</code>, where
        'Area' is the <a href="help?page=terms#kc_model">KC
        model</a> name for that knowledge component. The <strong>KC</strong> column should always be
        of the format <code>KC (kc_model_name)</code>. The model name must be &le; 50 characters and
        consist of letters, numbers, dashes, underscores, and spaces. If a KC model name is not
        included, the name will default to "Default". Multiple KC columns are OK.</td>
        <td>&le; 65,535</td>
      </tr>
      <tr>
        <td>KC Category ()</td>
        <td></td>
        <td>A <em>knowledge component category</em>. An example of the correct use of this column
        heading could be <code>KC Category (Area)</code>, where 'Area' is the KC model name for that
        knowledge component. The KC Category column should always be of the format <code>KC
        Category (kc_model_name)</code>. The model name must be &le; 30 characters and consist of
        letters, numbers, dashes, underscores, and spaces. If a KC model name is not included, the
        name will default to "Default". If including KC Category, be sure to pair it with a
        corresponding KC column by using the same KC model name. (Condition Name and Type must be
        paired together in the same way.) If you specify a a KC Category value, a KC value must be
        given as well. Multiple KC Category columns are OK.</td>
        <td>&le; 50</td>
      </tr>
      <tr class="odd">
        <td>School</td>
        <td></td>
        <td>The school in which the data were collected, if applicable.</td>
        <td>&le; 100</td>
      </tr>
      <tr>
        <td>Class</td>
        <td></td>
        <td>The class in which the data were collected, if applicable.</td>
        <td>&le; 75</td>
      </tr>
      <tr class="odd">
        <td>CF ()</td>
        <td></td>
        <td>A <a href="help?page=customFields">custom Field</a>. Use this element to describe other contextual information or a
        new variable not adequately captured by the other columns. An example of the correct use of
        this column heading could be <code>CF (Factor or add-m)</code>, where 'Factor or add-m' is
        the name for that custom field. The <strong>CF</strong> column should always be of the
        format <code>CF (custom_field_name)</code>. The custom field name must be &le; 65,000 characters
        and consist of letters, numbers, dashes, underscores, and spaces. If a custom field name is
        not included, the name will default to "Default". Multiple CF columns are OK.</td>
        <td>&le; 65,000</td>
      </tr>
    </tbody>
    </table>

    <div id="table-notes">

    <p id="note-1"><strong>&dagger;</strong> At least one of <em>Step Name</em>, <em>Selection</em>, or <em>Action</em> must
    have a value for each row.</p>

    <p id="note-2"><strong>[1] Time</strong> must be given in one of the following formats:</p>

    <table id="time-format-table">
        <colgroup>
            <col style="width: 17em" />
            <col style="width: 37em" />
        </colgroup>
        <thead>
            <tr>
                <th>Format</th>
                <th>Example and Notes</th>
            </tr>
        </thead>
        <tbody>
            <tr><td><code>yyyy-MM-dd HH:mm:ss.SSS</code></td><td>2001-07-04 12:08:56.0 ** OLI and DataShop export format</td></tr>
            <tr><td><code>yyyy-MM-dd HH:mm:ss:SSS</code></td><td>2001-07-04 12:08:39:110 ** Carnegie Learning format</td></tr>
            <tr><td><code>yyyy-MM-dd HH:mm:ss</code></td><td>2001-07-04 12:08:56 ** CTAT Flash format</td></tr>
            <tr><td><code>yyyy-MM-dd HH:mm</code></td><td>2001-07-04 12:08</td></tr>
            <tr><td><code>MMMMM dd, yyyy hh:mm:ss a</code></td><td>July 04, 2001 12:08:56 AM ** WPI-Assistments format</td></tr>
            <tr><td><code>MM/dd/yyyy HH:mm:ss</code></td><td>2/24/2007 17:18:02</td></tr>
            <tr><td><code>MM/dd/yyyy HH:mm</code></td><td>2/24/2007 17:18</td></tr>
            <tr><td><code>MM/dd/yy HH:mm:ss:SSS</code></td><td>07/04/01 12:08:56:322</td>
            <tr><td><code>MM/dd/yy HH:mm:ss</code></td><td>07/04/01 12:08:56</td>
            <tr><td><code>MM/dd/yy HH:mm</code></td><td>07/04/01 12:08</td>
            <tr><td><code>yyyy/MM/dd HH:mm:ss.SSS</code></td><td>2010/05/11 16:06:28.65 ** CTAT Java format</td>
            <tr><td><code>long</code></td><td>1239939193 ** Unix time in milliseconds</td></tr>
            <tr><td><code>double</code></td><td>01239939193.31 ** Unix time in milliseconds</td></tr>
            <tr><th style="padding-top:1em;text-align:center"><span style="background-color:#ffcccc">Bad formats</span></th><th></th></tr>
            <tr><td><code style="color:red">mm:ss.0</code></td><td><code style="color:red">08:56.0</code>
            <br /><strong>This date-less format is the result of Excel applying its own formatting. You may see this format
            if you opened and saved a DataShop transaction export file in Excel, but didn't apply TEXT formatting to the
            columns while opening it.
            See <a href="help?page=export#excel_warning">our advice
            on how to avoid this issue</a>. To correct it, you will need to find a copy of your file that has date information.</strong></td></tr>
        </tbody>
    </table>

     <p id="note-3"><strong>[2]</strong> For columns that are required as pairs&mdash;
     <strong>Condition Name</strong> and <strong>Condition Type</strong>, or
     <strong>KC</strong> and <strong>KC Category</strong>&mdash;these columns must be listed in the
     order that they are paired. For example, if a dataset file has two condition columns, the column
     format would be Condition Name, Condition Type, Condition Name, Condition Type.
     </p>
   </div>