/*
* Carnegie Mellon University, Human Computer Interaction Institute
* Copyright 2007
* All Rights Reserved
*/

package edu.cmu.pslc.datashop.servlet.learningcurve;

import org.jfree.chart.imagemap.ToolTipTagFragmentGenerator;

/**
 * Override of the StandardToolTipFragmentGenerator.
 *
 * @author Kyle A Cunningham
 * @version $Revision: 4765 $
 * <BR>Last modified by: $Author: bkb $
 * <BR>Last modified on: $Date: 2008-05-01 10:52:19 -0400 (Thu, 01 May 2008) $
 * <!-- $KeyWordsOff: $ -->
 */

public class LearningCurveToolTipFragmentGenerator implements
        ToolTipTagFragmentGenerator {

    /**
     * Generate the tool tip.  For this report just return the string generated by the label.
     * @param toolTipText string generated by the labeler.
     * @return String the string to apply to the element as a tool tip.
     */
    public String generateToolTipFragment(String toolTipText) {
        return toolTipText;
    }

}
