/*
 * Carnegie Mellon University, Human Computer Interaction Institute
 * Copyright 2013
 * All Rights Reserved
 */

package edu.cmu.pslc.importdata;

import java.util.ArrayList;

/**
 * Utility class that holds constants used by FFI HeadingReport to check 
 * for the use of MySQL reserved keywords.
 *
 * @author 
 * @version $Revision: 10435 $
 * <BR>Last modified by: $Author: alida $
 * <BR>Last modified on: $Date: 2013-12-19 10:07:17 -0500 (Thu, 19 Dec 2013) $
 * <!-- $KeyWordsOff: $ -->
  */

public final class ReservedKeywordConstants {

    /*****************************
     * Reserved Keyword Constants
     *****************************/
    public static final String ACCESSIBLE = "Accessible";
    public static final String ADD = "Add";
    public static final String ALL = "All";
    public static final String ALTER = "Alter";
    public static final String ANALYZE = "Analyze";
    public static final String AND = "And";
    public static final String AS = "As";
    public static final String ASC = "Asc";
    public static final String ASENSITIVE = "Asensitive";
    public static final String BEFORE = "Before";
    public static final String BETWEEN = "Between";
    public static final String BIGINT = "Bigint";
    public static final String BINARY = "Binary";
    public static final String BLOB = "Blob";
    public static final String BOTH = "Both";
    public static final String BY = "By";
    public static final String CALL = "Call";
    public static final String CASCADE = "Cascade";
    public static final String CASE = "Case";
    public static final String CHANGE = "Change";
    public static final String CHAR = "Char";
    public static final String CHARACTER = "Character";
    public static final String CHECK = "Check";
    public static final String COLLATE = "Collate";
    public static final String COLUMN = "Column";
    public static final String CONDITION = "Condition";
    public static final String CONNECTION = "Connection";
    public static final String CONSTRAINT = "Constraint";
    public static final String CONTINUE = "Continue";
    public static final String CONVERT = "Convert";
    public static final String CREATE = "Create";
    public static final String CROSS = "Cross";
    public static final String CURRENT_DATE = "Current Date";
    public static final String CURRENT_TIME = "Current Time";
    public static final String CURRENT_TIMESTAMP = "Current Timestamp";
    public static final String CURRENT_USER = "Current User";
    public static final String CURSOR = "Cursor";
    public static final String DATABASE = "Database";
    public static final String DATABASES = "Databases";
    public static final String DAY_HOUR = "Day Hour";
    public static final String DAY_MICROSECOND = "Day Microsecond"; 
    public static final String DAY_MINUTE = "Day Minute";
    public static final String DAY_SECOND = "Day Second";
    public static final String DEC = "Dec";
    public static final String DECIMAL = "Decimal";
    public static final String DECLARE = "Declare";
    public static final String DEFAULT = "Default";
    public static final String DELAYED = "Delayed";
    public static final String DELETE = "Delete";
    public static final String DESC = "Desc";
    public static final String DESCRIBE = "Describe";
    public static final String DETERMINISTIC = "Deterministic";
    public static final String DISTINCT = "Distinct";
    public static final String DISTINCTROW = "DistinctRow";
    public static final String DIV = "Div";
    public static final String DOUBLE = "Double";  
    public static final String DROP = "Drop";
    public static final String DUAL = "Dual";
    public static final String EACH = "Each";
    public static final String ELSE = "Else";
    public static final String ELSEIF = "ElseIf";
    public static final String ENCLOSED = "Enclosed";
    public static final String ESCAPED = "Escaped";
    public static final String EXISTS = "Exists";
    public static final String EXIT = "Exit";
    public static final String EXPLAIN = "Explain";
    public static final String FALSE = "False";
    public static final String FETCH = "Fetch";
    public static final String FLOAT = "Float";
    public static final String FLOAT4 = "Float4";
    public static final String FLOAT8 = "Float8";
    public static final String FOR = "For";
    public static final String FORCE = "Force";
    public static final String FOREIGN = "Foreign";
    public static final String FROM = "From";
    public static final String FULLTEXT = "FullText";
    public static final String GOTO = "Goto";
    public static final String GRANT = "Grant";
    public static final String GROUP = "Group";
    public static final String HAVING = "Having";
    public static final String HIGH_PRIORITY = "High Priority";
    public static final String HOUR_MICROSECOND = "Hour Microsecond";
    public static final String HOUR_MINUTE = "Hour Minute";
    public static final String HOUR_SECOND = "Hour Second";
    public static final String IF = "If";
    public static final String IGNORE = "Ignore";    
    public static final String IN = "In";
    public static final String INDEX = "Index";
    public static final String INFILE = "InFile";
    public static final String INNER = "Inner";
    public static final String INOUT = "InOut";
    public static final String INSENSITIVE = "Insensitive";   
    public static final String INSERT = "Insert";
    public static final String INT = "Int";
    public static final String INT1 = "Int1";
    public static final String INT2 = "Int2";
    public static final String INT3 = "Int3";
    public static final String INT4 = "Int4";
    public static final String INT8 = "Int8";
    public static final String INTEGER = "Integer";
    public static final String INTERVAL = "Interval";
    public static final String INTO = "Into";
    public static final String IS = "Is";
    public static final String ITERATE = "Iterate";
    public static final String JOIN = "Join";
    public static final String KEY = "Key";
    public static final String KEYS = "Keys";
    public static final String KILL = "Kill";
    public static final String LABEL = "Label";
    public static final String LEADING = "Leading";
    public static final String LEAVE = "Leave";
    public static final String LEFT = "Left";
    public static final String LIKE = "Like";
    public static final String LIMIT = "Limit";
    public static final String LINEAR = "Linear";
    public static final String LINES = "Lines";
    public static final String LOAD = "Load";
    public static final String LOCALTIME = "LocalTime";
    public static final String LOCALTIMESTAMP = "LocalTimestamp";
    public static final String LOCK = "Lock";
    public static final String LONG = "Long";
    public static final String LONGBLOB = "LongBlob";  
    public static final String LONGTEXT = "LongText";
    public static final String LOOP = "Loop";
    public static final String LOW_PRIORITY = "Low Priority";
    public static final String MASTER_SSL_VERIFY_SERVER_CERT = "Master SSL Verify Server Cert";
    public static final String MATCH = "Match";
    public static final String MEDIUMBLOB = "MediumBlob";  
    public static final String MEDIUMINT = "MediumInt";
    public static final String MEDIUMTEXT = "MediumText";
    public static final String MIDDLEINT = "MiddleInt";
    public static final String MINUTE_MICROSECOND = "Minute Microsecond";
    public static final String MINUTE_SECOND = "Minute Second";
    public static final String MOD = "Mod";
    public static final String MODIFIES = "Modifies";
    public static final String NATURAL = "Natural";
    public static final String NOT = "Not";
    public static final String NO_WRITE_TO_BINLOG = "No Write To BinLog";
    public static final String NULL = "Null";
    public static final String NUMERIC = "Numeric"; 
    public static final String ON = "On";
    public static final String OPTIMIZE = "Optimize";
    public static final String OPTION = "Option";
    public static final String OPTIONALLY = "Optionally";
    public static final String OR = "Or";
    public static final String ORDER = "Order";   
    public static final String OUT = "Out";
    public static final String OUTER = "Outer";
    public static final String OUTFILE = "Outfile";
    public static final String PRECISION = "Precision";
    public static final String PRIMARY = "Primary";
    public static final String PROCEDURE = "Procedure";
    public static final String PURGE = "Purge";
    public static final String RANGE = "Range";
    public static final String READ = "Read";
    public static final String READS = "Reads";
    public static final String READ_ONLY = "Read Only";
    public static final String READ_WRITE = "Read Write";
    public static final String REAL = "Real";
    public static final String REFERENCES = "References";
    public static final String REGEXP = "Regexp";
    public static final String RELEASE = "Release";
    public static final String RENAME = "Rename";
    public static final String REPEAT = "Repeat";
    public static final String REPLACE = "Replace";
    public static final String REQUIRE = "Require";
    public static final String RESTRICT = "Restrict";
    public static final String RETURN = "Return";
    public static final String REVOKE = "Revoke";
    public static final String RIGHT = "Right";
    public static final String RLIKE = "Rlike";
    public static final String SCHEMA = "Schema";
    public static final String SCHEMAS = "Schemas";
    public static final String SECOND_MICROSECOND = "Second Microsecond";
    public static final String SELECT = "Select";
    public static final String SENSITIVE = "Sensitive";
    public static final String SEPARATOR = "Separator";
    public static final String SET = "Set";
    public static final String SHOW = "Show";
    public static final String SMALLINT = "SmallInt";
    public static final String SPATIAL = "Spatial";
    public static final String SPECIFIC = "Specific";
    public static final String SQL = "Sql";
    public static final String SQLEXCEPTION = "SqlException";
    public static final String SQLSTATE = "SqlState";
    public static final String SQLWARNING = "SqlWarning";
    public static final String SQL_BIG_RESULT = "Sql Big Result";
    public static final String SQL_CALC_FOUND_ROWS = "Sql Calc Found Rows";
    public static final String SQL_SMALL_RESULT = "Sql Small Result";
    public static final String SSL = "Ssl";
    public static final String STARTING = "Starting";    
    public static final String STRAIGHT_JOIN = "Straight Join";
    public static final String TABLE = "Table";
    public static final String TERMINATED = "Terminated";  
    public static final String THEN = "Then";
    public static final String TINYBLOB = "TinyBlob";
    public static final String TINYINT = "TinyInt";
    public static final String TINYTEXT = "TinyText";
    public static final String TO = "To";
    public static final String TRAILING = "Trailing";
    public static final String TRIGGER = "Trigger";
    public static final String TRUE = "True";
    public static final String UNDO = "Undo";
    public static final String UNION = "Union";
    public static final String UNIQUE = "Unique";
    public static final String UNLOCK = "Unlock";
    public static final String UNSIGNED = "Unsigned";
    public static final String UPDATE = "Update";
    public static final String UPGRADE = "Upgrade";
    public static final String USAGE = "Usage";
    public static final String USE = "Use";
    public static final String USING = "Using"; 
    public static final String UTC_DATE = "UTC Date";
    public static final String UTC_TIME = "UTC Time";
    public static final String UTC_TIMESTAMP = "UTC Timestamp";
    public static final String VALUES = "Values";
    public static final String VARBINARY = "Varbinary";
    public static final String VARCHAR = "Varchar";
    public static final String VARCHARACTER = "VarCharacter";
    public static final String VARYING = "Varying";
    public static final String WHEN = "When";
    public static final String WHERE = "Where";
    public static final String WHILE = "While";
    public static final String WITH = "With";
    public static final String WRITE = "Write";
    public static final String XOR = "Xor";
    public static final String YEAR_MONTH = "Year Month";
    public static final String ZEROFILL = "ZeroFill";

    /** Reserved keywords. */
    public static final ArrayList<String> RESERVED_KEYWORDS =
        new ArrayList<String>() { { add(ACCESSIBLE);
                                    add(ADD);
                                    add(ALL);
                                    add(ALTER);
                                    add(ANALYZE);
                                    add(AND);
                                    add(AS);
                                    add(ASC);
                                    add(ASENSITIVE);
                                    add(BEFORE);
                                    add(BETWEEN);
                                    add(BIGINT);
                                    add(BINARY);
                                    add(BLOB);
                                    add(BOTH);
                                    add(BY);
                                    add(CALL);
                                    add(CASCADE);
                                    add(CASE);
                                    add(CHANGE);
                                    add(CHAR);
                                    add(CHARACTER);
                                    add(CHECK);
                                    add(COLLATE);
                                    add(COLUMN);
                                    add(CONDITION);
                                    add(CONNECTION);
                                    add(CONSTRAINT);
                                    add(CONTINUE);
                                    add(CONVERT);
                                    add(CREATE);
                                    add(CROSS);
                                    add(CURRENT_DATE);
                                    add(CURRENT_TIME);
                                    add(CURRENT_TIMESTAMP);
                                    add(CURRENT_USER);
                                    add(CURSOR);
                                    add(DATABASE);
                                    add(DATABASES);
                                    add(DAY_HOUR);
                                    add(DAY_MICROSECOND);
                                    add(DAY_MINUTE);
                                    add(DAY_SECOND);
                                    add(DEC);
                                    add(DECIMAL);
                                    add(DECLARE);
                                    add(DEFAULT);
                                    add(DELAYED);
                                    add(DELETE);
                                    add(DESC);
                                    add(DESCRIBE);
                                    add(DETERMINISTIC);
                                    add(DISTINCT);
                                    add(DISTINCTROW);
                                    add(DIV);
                                    add(DOUBLE);
                                    add(DROP);
                                    add(DUAL);
                                    add(EACH);
                                    add(ELSE);
                                    add(ELSEIF);
                                    add(ENCLOSED);
                                    add(ESCAPED);
                                    add(EXISTS);
                                    add(EXIT);
                                    add(EXPLAIN);
                                    add(FALSE);
                                    add(FETCH);
                                    add(FLOAT);
                                    add(FLOAT4);
                                    add(FLOAT8);
                                    add(FOR);
                                    add(FORCE);
                                    add(FOREIGN);
                                    add(FROM);
                                    add(FULLTEXT);
                                    add(GOTO);
                                    add(GRANT);
                                    add(GROUP);
                                    add(HAVING);
                                    add(HIGH_PRIORITY);
                                    add(HOUR_MICROSECOND);
                                    add(HOUR_MINUTE);
                                    add(HOUR_SECOND);
                                    add(IF);
                                    add(IGNORE);
                                    add(IN);
                                    add(INDEX);
                                    add(INFILE);
                                    add(INNER);
                                    add(INOUT);
                                    add(INSENSITIVE);
                                    add(INSERT);
                                    add(INT);
                                    add(INT1);
                                    add(INT2);
                                    add(INT3);
                                    add(INT4);
                                    add(INT8);
                                    add(INTEGER);
                                    add(INTERVAL);
                                    add(INTO);
                                    add(IS);
                                    add(ITERATE);
                                    add(JOIN);
                                    add(KEY);
                                    add(KEYS);
                                    add(KILL);
                                    add(LABEL);
                                    add(LEADING);
                                    add(LEAVE);
                                    add(LEFT);
                                    add(LIKE);
                                    add(LIMIT);
                                    add(LINEAR);
                                    add(LINES);
                                    add(LOAD);
                                    add(LOCALTIME);
                                    add(LOCALTIMESTAMP);
                                    add(LOCK);
                                    add(LONG);
                                    add(LONGBLOB);
                                    add(LONGTEXT);
                                    add(LOOP);
                                    add(LOW_PRIORITY);
                                    add(MASTER_SSL_VERIFY_SERVER_CERT);
                                    add(MATCH);
                                    add(MEDIUMBLOB);
                                    add(MEDIUMINT);
                                    add(MEDIUMTEXT);
                                    add(MIDDLEINT);
                                    add(MINUTE_MICROSECOND);
                                    add(MINUTE_MICROSECOND);
                                    add(MOD);
                                    add(MODIFIES);
                                    add(NATURAL);
                                    add(NOT);
                                    add(NO_WRITE_TO_BINLOG);
                                    add(NULL);
                                    add(NUMERIC);
                                    add(ON);
                                    add(OPTIMIZE);
                                    add(OPTION);
                                    add(OPTIONALLY);
                                    add(OR);
                                    add(ORDER);
                                    add(OUT);
                                    add(OUTER);
                                    add(OUTFILE);
                                    add(PRECISION);
                                    add(PRIMARY);
                                    add(PROCEDURE);
                                    add(PURGE);
                                    add(RANGE);
                                    add(READ);
                                    add(READS);
                                    add(READ_ONLY);
                                    add(READ_WRITE);
                                    add(REAL);
                                    add(REFERENCES);
                                    add(REGEXP);
                                    add(RELEASE);
                                    add(RENAME);
                                    add(REPEAT);
                                    add(REPLACE);
                                    add(REQUIRE);
                                    add(RESTRICT);
                                    add(RETURN);
                                    add(REVOKE);
                                    add(RIGHT);
                                    add(RLIKE);
                                    add(SCHEMA);
                                    add(SCHEMAS);
                                    add(SECOND_MICROSECOND);
                                    add(SELECT);
                                    add(SENSITIVE);
                                    add(SEPARATOR);
                                    add(SET);
                                    add(SHOW);
                                    add(SMALLINT);
                                    add(SPATIAL);
                                    add(SPECIFIC);
                                    add(SQL);
                                    add(SQLEXCEPTION);
                                    add(SQLSTATE);
                                    add(SQLWARNING);
                                    add(SQL_BIG_RESULT);
                                    add(SQL_CALC_FOUND_ROWS);
                                    add(SQL_SMALL_RESULT);
                                    add(SSL);
                                    add(STARTING);
                                    add(STRAIGHT_JOIN);
                                    add(TABLE);
                                    add(TERMINATED);
                                    add(THEN);
                                    add(TINYBLOB);
                                    add(TINYINT);
                                    add(TINYTEXT);
                                    add(TO);
                                    add(TRAILING);
                                    add(TRIGGER);
                                    add(TRUE);
                                    add(UNDO);
                                    add(UNION);
                                    add(UNIQUE);
                                    add(UNLOCK);
                                    add(UNSIGNED);
                                    add(UPDATE);
                                    add(UPGRADE);
                                    add(USAGE);
                                    add(USE);
                                    add(USING);
                                    add(UTC_DATE);
                                    add(UTC_TIME);
                                    add(UTC_TIMESTAMP);
                                    add(VALUES);
                                    add(VARBINARY);
                                    add(VARCHAR);
                                    add(VARCHARACTER);
                                    add(VARYING);
                                    add(WHEN);
                                    add(WHERE);
                                    add(WHILE);
                                    add(WITH);
                                    add(WRITE);
                                    add(XOR);
                                    add(YEAR_MONTH);
                                    add(ZEROFILL); } };

    /**
     * Private Constructor, as this is a utility class.
     */
    private ReservedKeywordConstants() { };

} // end ReservedKeywordConstants
